export const FETCH_CONDENSE_USER_INFO = "FETCH_CONDENSE_USER_INFO";
export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const FETCH_SUBSPACES = "FETCH_SUBSPACES";
export const CREATE_SUBSPACE = "CEATE_SUBSPACE";
export const JOIN_SUBSPACE = "JOIN_SUBSPACE";
export const DELETE_SUBSPACE = "DELETE_SUBSPACE";