// Styling for SubspaceForm.jsx
const styles = () => ({
    resetBtn: {
        "&:hover": {
            backgroundColor: "button.secondary",
            color: "button.primary",
        },
    },
    createBtn: {
        bgcolor: "#0090c1",
        color: "#ffffff",
        marginLeft: "8px",
        "&:hover": {
            backgroundColor: "button.secondary",
            color: "button.primary",
        },
    },
    stepperContainer: {
        width: "auto",
        minWidth: { xs: "99%", md: "65%", lg: "75%" },
        margin: "0 auto",
        padding: { xs: "4px 16px 8px 4px", sm: "32px 16px" },
        position: "fixed",
        bottom: "0px",
        left: { xs: "0", md: "auto" },
        right: { xs: "0", md: "auto" },
        bgcolor: "background.default",
    },
    topicsContainer: {
        "@media (min-width: 900px)": {
            width: "600px",
            position: "absolute",
        },
    },
    selectedChipContainer: { bgcolor: "background.secondary", borderRadius: "16px", padding: "4px 8px", maxHeight: "15vh", overflow: "scroll" },
    selectedChipContainerArray: { padding: "2px 0", display: "flex", flexWrap: "wrap", gap: "5px" },
    chipContainer: { display: "flex", justifyContent: "start", flexWrap: "wrap", gap: "5px", maxHeight: "25vh", overflow: "scroll" },
    chipDivider: { height: "2px", width: "100%", flexBasis: "100%", margin: "4px 0" },
    profileContainer: {
        height: { xs: "175px", lg: "325px" },
        width: { xs: "auto", sm: "500px" },
        marginRight: { xs: "16px", sm: "0" },
        padding: { xs: "0 8px", sm: "4px 12px" },
        borderRadius: "10px",
        bgcolor: "background.tertiary",
        boxShadow: "rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px",
        marginBottom: "0",
        position: { xs: "absolute", lg: "relative" },
        top: { xs: "110px", sm: "145px", lg: "0" },
        overflow: "scroll",
    },
    bioContainer: {
        height: "155px",
        width: { xs: "100%", md: "550px", lg: "175px" },
        paddingTop: "4px",
        wordBreak: "break-word",
        overflow: "auto",
        overflowWrap: "break-word",
        hyphens: "auto",
    },
    flexContainer: { display: "flex", alignItems: "end" },
    mainContainer: { display: "flex", gap: "8px", alignItems: "center" },
    avatarContainer: { bgcolor: "background.primary", padding: "2px", borderRadius: "50%" },
    subspaceString: { fontSize: "12px", width: "18px", minWidth: "18px", paddingBottom: "3px" },
    customSubspaceName: { fontSize: { lg: "14px" }, paddingBottom: "3px" },
    gridItemBox: { padding: "8px 0", wordBreak: "break-all", hyphens: "auto", whiteSpace: "pre-line" },
    gridItemTitle: { fontSize: "12px" },
    updateModal: {
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        width: 400,
        bgcolor: "background.paper",
        border: "2px solid #000",
        boxShadow: 24,
        p: 4,
    },
});

export default styles;